version: '3.7'
services:
  db:
    image: postgres
    container_name: habits_db
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file: .env-non-dev
    ports:
      - 5432:5432

  redis:
    image: redis
    container_name: habits_redis

  app:
    container_name: habits_app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    env_file:
      - .env-non-dev
    tty: true
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 127.0.0.1:8000"
    ports:
      - '8000:8000'
    volumes:
      - .:/code

  celery:
    build:
      context: .
    depends_on:
      - app
    tty: true
    container_name: app_celery
    env_file: .env-non-dev
    command: celery -A config worker -l INFO -S django

  celery-beat:
    build:
      context: .
    container_name: app_celery_beat
    tty: true
    env_file: .env-non-dev
    command: celery -A config beat -l INFO -S django
    depends_on:
      - app
volumes:
  pg_data: